import { createSourceAdapter } from "@/lib/migration/adapters/create-adapter";

export const GENERIC_HEADER_ALIASES: Record<string, string[]> = {
  fullName: ["name", "full_name", "contact_name", "seller_name", "owner_name"],
  firstName: ["first_name", "firstname", "first"],
  lastName: ["last_name", "lastname", "last"],
  email: ["email", "email_address"],
  phone: ["phone", "phone_number", "mobile", "cell", "primary_phone"],
  company: ["company", "organization"],
  source: ["source", "lead_source"],
  title: ["title", "lead_title", "opportunity"],
  value: ["value", "deal_value", "amount"],
  pipelineStageName: ["pipeline_stage", "stage", "status", "deal_stage"],
  tags: ["tags", "labels", "tag"],
  addressLine1: [
    "property_address",
    "address",
    "address_line1",
    "street_address",
  ],
  addressLine2: ["address_line2", "unit", "suite"],
  city: ["property_city", "city"],
  state: ["property_state", "state"],
  postalCode: ["property_zip", "property_postal_code", "postal_code", "zip", "zip_code"],
  propertyType: ["property_type", "type"],
  bedrooms: ["bedrooms", "beds"],
  bathrooms: ["bathrooms", "baths"],
  squareFeet: ["square_feet", "sqft", "area", "square_footage"],
  askingPrice: ["asking_price", "list_price"],
  estimatedValue: ["estimated_value", "property_value", "arv"],
  contractStatus: ["contract_status"],
  contractAmount: ["contract_amount", "contract_price"],
  contractCloseDate: ["contract_close_date", "close_date"],
  condition: ["condition", "property_condition", "overall_condition"],
  updatesDone: ["updates_done", "recent_updates"],
  updatesNeeded: ["updates_needed", "repairs_needed"],
  occupancyStatus: ["occupancy", "occupancy_status"],
  tenantDurationRent: ["tenant_duration_rent", "rent", "lease_terms"],
  motivation: ["motivation", "seller_motivation", "reason_for_selling"],
  timeline: ["timeline", "desired_timeline"],
  workNeeded: ["work_needed", "repairs"],
  roofCondition: ["roof", "roof_condition"],
  flooringCondition: ["flooring", "flooring_condition"],
  kitchenBathCondition: ["kitchen_bath", "kitchen_bath_condition"],
  mortgage: ["mortgage", "mortgage_balance", "loan_balance"],
  frameSidingCondition: ["frame_siding", "siding", "frame_siding_condition"],
  windowsCondition: ["windows", "windows_condition"],
  basementType: ["basement", "basement_type"],
  wallsCondition: ["walls", "walls_condition"],
  electricalPlumbingCondition: ["electrical_plumbing", "electrical", "plumbing"],
  furnaceCondition: ["furnace", "furnace_condition", "hvac"],
  waterHeaterCondition: ["water_heater", "water_heater_condition"],
  acCondition: ["ac", "air_conditioning", "ac_condition"],
  followUpContact: ["follow_up_contact", "follow_up", "next_contact"],
  notes: ["notes", "property_notes", "property_note", "general_notes"],
};

export const genericAdapter = createSourceAdapter({
  id: "generic",
  label: "Generic CSV",
  headerAliases: GENERIC_HEADER_ALIASES,
});
