export function getInboundEmailDomain(): string | null {
  const domain = process.env.INBOUND_EMAIL_DOMAIN?.trim().toLowerCase();
  return domain || null;
}

export function buildReplyToAddress(token: string): string {
  const domain = getInboundEmailDomain();
  if (!domain) {
    throw new Error("INBOUND_EMAIL_DOMAIN is not configured");
  }
  return `replies+${token}@${domain}`;
}

export function parseTokenFromAddress(address: string): string | null {
  const normalized = address.trim().toLowerCase();
  const angleMatch = normalized.match(/<([^>]+)>/);
  const email = angleMatch ? angleMatch[1] : normalized;
  const localPart = email.split("@")[0] ?? "";
  const match = localPart.match(/^replies\+(.+)$/i);
  return match?.[1] ?? null;
}

export function parseTokenFromAddresses(addresses: string[]): string | null {
  for (const address of addresses) {
    const token = parseTokenFromAddress(address);
    if (token) {
      return token;
    }
  }
  return null;
}

export function getInboundAddressPattern(): string | null {
  const domain = getInboundEmailDomain();
  if (!domain) {
    return null;
  }
  return `replies+<auto-generated>@${domain}`;
}
